user = "tag"
version = "4.1.0"
last_push_time = 2024-09-20T15:25:32.919754Z
last_push_artifact = -1
last_push_artifact_type = -1
last_commit_msg = "Updated <FuncHeader: unsigned long long None(args=0); @0x359c98>"
